
services:

  postgres:
    image: postgres:15
    container_name: fintrack-postgres
    restart: always
    environment:
      POSTGRES_DB: fintrack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: osaahmed
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: saqibahmeddocker/fintrack-app:1.0
    platform: linux/amd64
    container_name: fintrack-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fintrack
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: osaahmed

volumes:
  pgdata:
